### ISSUE TITLE
Architecture error: Raspi3

### ISSUE THREAD

**Issue by Mason10198** [rfgamaral/docker-gphotos-uploader#1]
Attempting to run on Raspi3, everything works until I run the following for first startup of the container:
```
docker run -d \
--name=gphotos-uploader \
-v /home/pi/GPhotos/config:/config \
-v /home/pi/GPhotos/media:/photos \
--restart unless-stopped \
rfgamaral/gphotos-uploader
```
I can see the `/config` and `/photos` directories appear, but no `/config/config.hsjon` being created. If I run `docker logs -f gphotos-uploader` I get: 
```
$ docker logs -f gphotos-uploader
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"
```
Which is probably due to the `GOARCH=amd64` in the Dockerfile being incompatible with my architecture.

**Comment by Mason10198** [comment]
I tried forking the repo and building my own with the Dockerfile edited to `GOARCH=arm` but the problem is still occuring...

**Comment by Mason10198** [comment]
Fixed by cloning the repo and manually editing the Dockerfile to change all instances of `amd64` to `arm`.

**Comment by rfgamaral** [comment]
Hum, that's interesting. I'll need to look into how to build multi-architecture Docker images. One question, did you change only `GOARCH`? What about the `s6-overlay`, did you change that one too?

**Comment by Mason10198** [comment]
I started out only changing `GOARCH` because I didn't see `s6-overlay`, but it wasn't working and it took me a while to find that `s6-overlay` needed to be changed too

**Comment by rfgamaral** [comment]
I'm trying to build multi-arch images with Docker Hub, meaning you just pull the image as usual and Docker will pick the proper architecture for you (if available). I'm focusing on arm builds for now but I'm having some issues, not sure if I'm doing something wrong or if there's a bug on Docker Hub's Automated Builds functionality. Stay tuned.

**Comment by rfgamaral** [comment]
@Mason10198 I believe I've fixed the issue and pushed multi-arch images to Docker Hub. Could you please just pull the latest image and see if it works for you? It should pull the correct architecture for your Raspberry Pi 3.

**Comment by rfgamaral** [comment]
I'm going to assume this is fixed, if it's not, please let me know.
