### ISSUE TITLE
FIles Not Uploading

### ISSUE THREAD

**Issue by ldbrownjr** [rfgamaral/docker-gphotos-uploader#12]
Hello, I have this docker installed on a synology nas and appear to be having an issue with the files uploading. Any thoughts are much appreciated!

My docker settings are:

```
{
   "cap_add" : null,
   "cap_drop" : null,
   "cmd" : "",
   "cpu_priority" : 50,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enabled" : true,
   "entrypoint_default" : "/init",
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "GPU_SCHEDULE",
         "value" : "0 */8 * * *"
      }
   ],
   "exporting" : false,
   "id" : "55d442804c1b51190ec3376045d27e65aff4acfd739a056e58563c4d4b129cee",
   "image" : "rfgamaral/gphotos-uploader:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 1073741824,
   "memory_limit_slider" : 1024,
   "name" : "gphotos-uploader",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 29070,
         "host_port" : 29070,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/Photos/Albums/test",
         "mount_point" : "/albums",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/gphotos_uploader",
         "mount_point" : "/config",
         "type" : "rw"
      }
   ]
}
```

And my config file is:
```
{
  SecretsBackendType: auto,
  APIAppCredentials: {
    ClientID:     "xxx.apps.googleusercontent.com",
    ClientSecret: "xxxx",
  }
  jobs: [
    {
      account: xxxx@gmail.com
      sourceFolder: /albums
      makeAlbums: {
        enabled: true
        use: folderNames
      }
      deleteAfterUpload: false
      uploadVideos: true
      includePatterns: [ "*.jpg", "*.png" ]
      excludePatterns: [ ".thumbs.db/*" ]
    }
  ]
}
```

when i run `docker exec -it gphotos-uploader run` i get:
```
2019/11/08 16:13:23 config doesn't allow to upload this item - skipping: file=/albums
2019/11/08 16:13:23 all uploads done
2019/11/08 16:13:23 all deletions done
```

It doesn't appear that it is finding any of the files within the mapped folder of `/albums` which is:

```
/albums
/albums/New Orleans
```

If I run `docker exec -it gphotos-uploader /bin/sh` and then:

```
/ # ls -l /albums
total 0
d---------    1 1026     users          788 Sep 14  2017 New Orleans
/ # ls -l "/albums/New Orleans"
total 1412
drwxrwxrwx    1 root     root            44 Nov  8 16:08 @eaDir
----------    1 1026     users       112201 Feb 17  2013 AnneRicesHome.jpg
----------    1 1026     users        57596 Feb 17  2013 BourbonStreet.jpg
----------    1 1026     users        65527 Feb 17  2013 QHBedroom.jpg
----------    1 1026     users            0 Feb 17  2013 QHCourtyardLarry.jpg
----------    1 1026     users        96986 Feb 17  2013 QHCourtyardLaura.jpg
----------    1 1026     users        70862 Feb 17  2013 QHKitchen.jpg
----------    1 1026     users        49267 Feb 17  2013 QHLivingRoom.jpg
----------    1 1026     users       104812 Feb 17  2013 QuarterHouseLobby.jpg
----------    1 1026     users       766084 Feb 17  2013 Run.jpg
----------    1 1026     users        71365 Feb 17  2013 TWWroteHere.jpg
----------    1 1026     users        27136 Mar 28  2010 Thumbs.db
```
It does seems odd to me that the permissions are all dashes.

**Comment by rfgamaral** [comment]
```
"host_volume_file" : "/Photos/Albums/test",
```

Shouldn't you be mounting `/Photos/Albums`?

**Comment by ldbrownjr** [comment]
I have the test folder set up with the New Orleans folder inside it. So on my actual system it is /Photos/Albums/test/New Orleans with images inside.

I have mounted the test folder to verify how things work.

I have a large library of other photos within /Photos/Albums. I didn’t want to start there until I confirm things working.

**Comment by rfgamaral** [comment]
> I have a large library of other photos within /Photos/Albums. I didn’t want to start there until I confirm things working.

It's understandable :)

> ```
> 2019/11/08 16:13:23 config doesn't allow to upload this item - skipping: file=/albums
> ```

Based on this error message it feels like the volume mounting was not done correctly. It feels like your `/albums` mapping is being interpreted as a file (for some reason) and `gphotos-uploader-cli` is right saying it can't upload such file type.

Can you please post the **exact** `docker` command (or `docker-compose`) you used to create the container?

**Comment by ldbrownjr** [comment]
I had created the container using synology's UI docker package. I'll delete it and try it from command line.

**Comment by ldbrownjr** [comment]
I've built the container with the below command.
```
docker run -d \
    --name=gphotos-uploader \
    -e GPU_SCHEDULE="0 */8 * * *" \
    -p 29070:29070 \
    -v /volume2/docker/gphotos_uploader:/config \
    -v /volume2/Photos/Albums/test:/albums \
    --restart unless-stopped \
    rfgamaral/gphotos-uploader
```
And I am having the same issue. I'm going to keep digging. It appears to be mounted correctly because when I go into the docker shell I can navigate around it no issues, see below. It still feels like a permissions issue on the files though. I'm going to see what I can do with that.
```
/volume2/docker/gphotos_uploader$ sudo docker exec -it gphotos-uploader /bin/sh
/ # ls
albums   config   etc      init     libexec  mnt      photos   root     sbin     sys      usr
bin      dev      home     lib      media    opt      proc     run      srv      tmp      var
/ # cd albums
/albums # ls
New Orleans
/albums # cd "New Orleans"
/albums/New Orleans # ls
@eaDir                 QHBedroom.jpg          QHKitchen.jpg          Run.jpg
AnneRicesHome.jpg      QHCourtyardLarry.jpg   QHLivingRoom.jpg       TWWroteHere.jpg
BourbonStreet.jpg      QHCourtyardLaura.jpg   QuarterHouseLobby.jpg  Thumbs.db
/albums/New Orleans # ls -l
total 1412
drwxrwxrwx    1 root     root            44 Nov  8 16:08 @eaDir
----------    1 1026     users       112201 Feb 17  2013 AnneRicesHome.jpg
----------    1 1026     users        57596 Feb 17  2013 BourbonStreet.jpg
----------    1 1026     users        65527 Feb 17  2013 QHBedroom.jpg
----------    1 1026     users            0 Feb 17  2013 QHCourtyardLarry.jpg
----------    1 1026     users        96986 Feb 17  2013 QHCourtyardLaura.jpg
----------    1 1026     users        70862 Feb 17  2013 QHKitchen.jpg
----------    1 1026     users        49267 Feb 17  2013 QHLivingRoom.jpg
----------    1 1026     users       104812 Feb 17  2013 QuarterHouseLobby.jpg
----------    1 1026     users       766084 Feb 17  2013 Run.jpg
----------    1 1026     users        71365 Feb 17  2013 TWWroteHere.jpg
----------    1 1026     users        27136 Mar 28  2010 Thumbs.db

```

**Comment by rfgamaral** [comment]
It could be a permissions/owner thing...

It looks like the owner of those files is a user that doesn't exist anymore (it's showing `1026` instead of the username). Check if the `docker` user has permissions to **read** your albums. From your output, it doesn't look like it has proper access.

**Comment by ldbrownjr** [comment]
Thank you for continuing to work with me on this. I'm really hoping to get this working.

`1026` is the owner `Larry Brown` of the files. Each file is also in the `users` group.  I have now modified the users group to have **read** access to my photos directories.

Below shows the updated permissions from cmd line. However, when **run** it still does not seem to be picking up the files to upload.

```
Larry Brown@xxx:~$ ls -l /volume2/Photos/Albums/test/
total 112
-rwxrwxrwx+ 1 Larry Brown users 112201 Feb 17  2013 AnneRicesHome.jpg
drwxrwxrwx+ 1 Larry Brown users    788 Sep 14  2017 New Orleans

Larry Brown@cybertron:~$ sudo docker exec -it gphotos-uploader /bin/sh

/ # ls -l /albums/
total 112
-r-xr-x---    1 1026     users       112201 Feb 17  2013 AnneRicesHome.jpg
dr-xr-x---    1 1026     users          788 Sep 14  2017 New Orleans

/ # run
2019/11/09 14:29:39 Token expiration: 2019-11-09 15:19:38.149366274 +0000 UTC
2019/11/09 14:29:39 config doesn't allow to upload this item - skipping: file=/albums
2019/11/09 14:29:39 all uploads done
2019/11/09 14:29:39 all deletions done
```

**Comment by ldbrownjr** [comment]
So I have found out this is not a permissions issue, but instead is with the `includePatterns` and `excludePatterns`.  I removed those from the config file completely and it started to try and upload everything. Now I just need to figure out the proper syntax to have in there. :)

**Comment by rfgamaral** [comment]
> 
> 
> So I have found out this is not a permissions issue, but instead is with the `includePatterns` and `excludePatterns`. I removed those from the config file completely and it started to try and upload everything. Now I just need to figure out the proper syntax to have in there. :)

Glad you got it working and I'm sorry I couldn't be of any more help.

Can I suggest you to open an issue in the upstream `gphotos-uplaoder-cli` repository about this? I mean, it doesn't seem there's anything wrong but the error message could be a little more descriptive and help people figure out what's really happening.

**Comment by ldbrownjr** [comment]
No worries. I will probably post something over there. 

I'm now trying to figure out a date issue (i'm seeing all photos showing up with the uploaded date instead of the date from exif data). I was about to post over there. However I found this issue reported back in 11/2018.  https://github.com/gphotosuploader/gphotos-uploader-cli/issues/20
Within there one person says it isn't happening anymore. Can you confirm what is the latest `gphotos-uploader-cli` version you have in this docker?

**Comment by ldbrownjr** [comment]
Correction. It is working good. I didn't realize that the month of photos I was testing with did in fact have a mix of photos with exif data and some didn't. All is good. Thank you for building the docker container for this!
