### ISSUE TITLE
Problem with authentication

### ISSUE THREAD

**Issue by HydrelioxGitHub** [rfgamaral/docker-gphotos-uploader#14]
**Describe the bug**
I've a problem with authenticating in docker. I've the message in my browser ( "You are authenticated, you can now return to the program. This will auto-close" ). But in the shell, I have the message : "

``` 
root@nas:~#` docker exec -it gphoto run                                                                                                                                                                             
[info]   Opening browser to complete authorization.

[warn]   Browser was not detected. Complete the authorization browsing to: http://localhost:29070

[error]  error while authorization: error while exchanging authorization code and token: Post 
https://oauth2.googleapis.com/token: x509: certificate signed by unknown authority

[fatal]  could not get a token: error while exchanging authorization code and token: Post https://oauth2.googleapis.com/token: x509: certificate signed by unknown authority
```

**Desktop & Client versions (please complete the following information):**
 - Docker

Precision : I'm running the container on a headless server. So I've got to authenticate through a browser on another machine. In the browse I get the success page but if I log the container I've got what I mentioned above.

**Comment by rfgamaral** [comment]
Please run this:

```
docker exec -it gphoto update-ca-certificates
```

And once it's finished try again with:

```
docker exec -it gphoto run 
```

**Comment by HydrelioxGitHub** [comment]
I've got an error on the first command : 

`root@nas:~# docker exec -it gphoto update-ca-certificates                 OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"update-ca-certificates\": executable file not found in $PATH": unknown`

**Comment by rfgamaral** [comment]
That's weird...

Please login to your container shell:

```
docker exec -it gphoto /bin/sh
```

And call `update-ca-certificates` directly inside the shell. If that doesn't work, while still in the shell do this:

```
apk add ca-certificates
```

And then call `update-ca-certificates` again and then try again:

```
docker exec -it gphoto run 
```

Also, which device are you installing `docker-gphotos-uploader`?

**Comment by HydrelioxGitHub** [comment]
There is a warning, but it seems something has been done.
`root@nas:~# docker exec -it gphoto /bin/sh                                
/ # apk add ca-certificates                                               
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/armv7/APKINDEX.tar.g
z                                                                         
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/armv7/APKINDEX.
tar.gz                                                                    
(1/1) Installing ca-certificates (20190108-r0)                            
Executing busybox-1.30.1-r2.trigger                                       
Executing ca-certificates-20190108-r0.trigger
OK: 4 MiB in 15 packages
/ # update-ca-certificates                                                
WARNING: ca-certificates.crt does not contain exactly one certificate or C
RL: skipping                                                              
/ # exit`

But there is permission error then 
`root@nas:~# docker exec -it gphoto run    [info]   Found item to upload: /photos/Voici Gohan/.picasa.ini
[info]   Found item to upload: /photos/Voici Gohan/2015-03-17.jpg
[info]   Found item to upload: /photos/Voici Gohan/IMG_20150315_104822.jpg
[info]   Found item to upload: /photos/Voici Gohan/IMG_20150315_104829.jpg
[info]   Found item to upload: /photos/Voici Gohan/IMG_20150315_104831.jpg
[info]   Found item to upload: /photos/Voici Gohan/IMG_20150315_104840.jpg
[info]   Found item to upload: /photos/Voici Gohan/IMG_20150315_104841.jpg
[info]   Found item to upload: /photos/Voici Gohan/IMG_20150315_104844.jpg
[info]   Found item to upload: /photos/Voici Gohan/IMG_20150315_104849.jpg
[info]   Found item to upload: /photos/Voici Gohan/IMG_20150315_104909.jpg
[info]   Found item to upload: /photos/Voici Gohan/IMG_20150315_105556.jpg
[info]   Found item to upload: /photos/Voici Gohan/IMG_20150315_105613.jpg
[info]   Found item to upload: /photos/Voici Gohan/IMG_20150315_110417.jpg
[info]   Found item to upload: /photos/Voici Gohan/IMG_20150315_110445.jpg
[info]   Found item to upload: /photos/Voici Gohan/VID_20150315_110420.mp4
[info]   15 files pending to be uploaded in folder '/photos'.
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/2015-03-17.jpg, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/2015-03-17.jpg
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/IMG_20150315_104822.jpg, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/IMG_20150315_104822.jpg
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/IMG_20150315_104829.jpg, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/IMG_20150315_104829.jpg
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/.picasa.ini, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/.picasa.ini
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/IMG_20150315_104849.jpg, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/IMG_20150315_104849.jpg
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/IMG_20150315_104831.jpg, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/IMG_20150315_104831.jpg
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/IMG_20150315_104840.jpg, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/IMG_20150315_104840.jpg
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/IMG_20150315_104841.jpg, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/IMG_20150315_104841.jpg
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/IMG_20150315_105613.jpg, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/IMG_20150315_105613.jpg
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/VID_20150315_110420.mp4, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/VID_20150315_110420.mp4
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/IMG_20150315_104909.jpg, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/IMG_20150315_104909.jpg
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/IMG_20150315_105556.jpg, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/IMG_20150315_105556.jpg
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/IMG_20150315_110417.jpg, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/IMG_20150315_110417.jpg
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/IMG_20150315_110445.jpg, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/IMG_20150315_110445.jpg
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/Voici Gohan/IMG_20150315_104844.jpg, err=googleapi: Error 400: No permission to add media items to this album., badRequest
[fail] X Error processing /photos/Voici Gohan/IMG_20150315_104844.jpg
[info]   15 processed files: 0 successfully, 15 with errors`

**Comment by rfgamaral** [comment]
But how did you got those errors? Were you able to authenticate?

**Comment by HydrelioxGitHub** [comment]
I just tried your command lines ( apk add certificate etc... ) then `docker exec -it gphoto run ` and do the same thing than explained above (Opening Browser .... etc ) and got on my browser the same message on authentication. 

I've just try to re-run and got this : https://pastebin.com/4K6qTasg

**Comment by rfgamaral** [comment]
So, you were able to authenticate, correct? I really need you to answer me this with a yes or no, I need to understand what's happening and what fixed your authentication problem.

**Comment by HydrelioxGitHub** [comment]
I think it's a yes. Through the browser I was able to authenticate.

**Comment by rfgamaral** [comment]
If the authentication problem is fixed, that's great, I might need to fix something on my Docker image, can you please just let me know which device are you using for this? A Raspberry Pi or something?

As for your uploading issue, that looks like an upstream issue and I recommend you open a new issue in the `gphotos-uploader-cli` repository, they should be able to help you better. But based on the error, there seems to be some problem with the album you're uploading to. Try to rename the folder name and try to upload again and see if that works.

**Comment by scadylan** [comment]
Hi  rfgamaral, I met the same problem.  My device is Synology DS918+ with docker.  I used you method and it success to run.  thanks!

**Comment by rfgamaral** [comment]
> Hi rfgamaral, I met the same problem. My device is Synology DS918+ with docker. I used you method and it success to run.

Just clarify something for me... You had the same authentication problem and you fixed with my suggestion above? Yes?

**Comment by scadylan** [comment]
Yes , it is fixed with you suggestion and it runs well. Thanks!

**Comment by rfgamaral** [comment]
> 
> 
> Yes , it is fixed with you suggestion and it runs well. Thanks!

Thank you, I'll need to provide a fix for that.

As for the other issue, I believe that's an upstream issue (maybe, not sure yet) and that's being tracked here: https://github.com/gphotosuploader/gphotos-uploader-cli/issues/49

**Comment by HydrelioxGitHub** [comment]
Maybe this issue can be closed as the error 400 problem is not really related to it ?

**Comment by rfgamaral** [comment]
Well, the original issue is not yet fixed in `master`, you guys only used a workaround to temporarily solve the problem on your end. I'll close this once I fix the authentication issue in `master` and release a new version with it :)

**Comment by HydrelioxGitHub** [comment]
I've made one test with some pictures and deleted them on Google Photo. Now these photo are not detected again as uploadable. How do I reset to re-upload them ?

**Comment by rfgamaral** [comment]
> 
> 
> I've made one test with some pictures and deleted them on Google Photo. Now these photo are not detected again as uploadable. How do I reset to re-upload them ?

I have no idea. You need to ask that in the `gphotos-uploader-cli` repository.

**Comment by suprimex** [comment]
Raspberry Pi3, Raspbian GNU/Linux 9.11 (stretch), 
just want to confirm that I had the same issue as the topic starter ( error about certificate signed by unknown authority)  and "apk add ca-certificates"  with "update-ca-certificates"  in container shell helped in this case. Thank you.

**Comment by rfgamaral** [comment]
Thank you for that @suprimex.

I'm going to publish a fixed version in a couple of minutes and close this once it's published.

**Comment by rfgamaral** [comment]
I just published a fixed version to the `preview` tag (and bumped the tool to the latest version), could any of you guys please test it out before I publish this to `latest`?
