### ISSUE TITLE
container does not run cron command

### ISSUE THREAD

**Issue by crp724** [rfgamaral/docker-gphotos-uploader#16]
so glad you created this docker!

While it runs great with invoking the command docker exec -it gphotos-uploader run from host - I cannot get the container to run the command from cron within the container. It is running gphotos-uploader-cli command from cron in the container - which does not upload photos. 

Any clues on how to fix this? 
Thanks

**Comment by rfgamaral** [comment]
Can you please try the `preview` version (instead of `latest` or a fixed version) I just uploaded to DockerHub and see if that solves the issue for you? Let me know how it goes. Thanks.

**Comment by crp724** [comment]
That fixed it! Thanks!!

**Comment by rfgamaral** [comment]
Great, will make a new production release and tag `latest` :)
