### ISSUE TITLE
Upload as  compressed video / photo to reduce used space on gdrive/gphotos

### ISSUE THREAD

**Issue by matze19999** [rfgamaral/docker-gphotos-uploader#18]
The tool uploads the videos as uncompressed files, which reduces the available storage on gdrive.

Can this be changed with a parameter?

**Comment by rfgamaral** [comment]
This project is just a container wrapping the actual tool that does all the work, [`gphotos-uploader-cli`](https://github.com/gphotosuploader/gphotos-uploader-cli). You need to raise that issue with the upstream project.
