### ISSUE TITLE
Update binary?

### ISSUE THREAD

**Issue by auanasgheps** [rfgamaral/docker-gphotos-uploader#19]
Hi
Are you still maintaining this container? gphotos-uploader-cli has reached v1.2.0 while this container is stuck to 1.0.6.

Thanks!

**Comment by splttingatms** [comment]
+1 I would like to use the tagged patterns for the include/exclude filters https://gphotosuploader.github.io/gphotos-uploader-cli/#/configuration?id=tagged-patterns but they weren't added until v2.0 https://github.com/gphotosuploader/gphotos-uploader-cli/blob/409fdc4f99994519ac20fff1f009e83cec81f551/CHANGELOG.md#200

**Comment by krosbow** [comment]
+1 as well, I'd do this although suspecting the differences between 1.0.6 and now 3.1.0 may need more than just the dockerfile version of gphotos-uploader-cli being updated. @rfgamaral and @mshish - thoughts?

**Comment by rfgamaral** [comment]
I'm not actively maintaining this container in the sense of keeping it up to date with the upstream project myself, as I currently lack the time to keep up with all the changes in `gphotos-uploader-cli`.

But I'm open to review PRs, and publish new versions if anyone wants to contribute :)

**Comment by auanasgheps** [comment]
I will try to play around with dockerfile versions, but the original CLI has advanced a lot and I'm not really an expert in building containers. Can't promise much but will try.

**Comment by auanasgheps** [comment]
I abandoned this container so I am closing this issue.
RIP.
