### ISSUE TITLE
Configuration file (config.hsjon) settings do not persist

### ISSUE THREAD

**Issue by cirrusflyer** [rfgamaral/docker-gphotos-uploader#3]
It seems that any changes I make to the config.hsjon file get overwritten everytime the docker vm restarts.  I have the folder mapped to the local folder.  Ideas?

**Comment by rfgamaral** [comment]
Can you please describe the necessary steps to try to reproduce the issue on my side?

**Comment by cirrusflyer** [comment]
I've edited the config file to add my Google API credentials and other setting changes in this file.  These changes get overwritten each time.

**Comment by rfgamaral** [comment]
I understand what the problem is. But I also need to understand the exact steps you're taking so I can try and replicate the problem on my side. What's the command you used to create and start the container? And more importantly, how are you restarting the container? Manually or automatically? How exactly?

**Comment by cirrusflyer** [comment]
When I restart the container manually, or perform the steps for API auth, the file loses it's info. I thought since it's a file with a volume map from the container to the local drive, any settings should remain.  thx

**Comment by rfgamaral** [comment]
> I thought since it's a file with a volume map from the container to the local drive, any settings should remain.

Yes, they should.

> When I restart the container manually, or perform the steps for API auth, the file loses it's info.

I can't seem to replicate your issue, sorry.

**Comment by cirrusflyer** [comment]
Can you share you volume settings?

On Feb 24, 2019, at 5:43 PM, Ricardo Amaral <notifications@github.com> wrote:

I thought since it's a file with a volume map from the container to the local drive, any settings should remain.

Yes, they should.

When I restart the container manually, or perform the steps for API auth, the file loses it's info.

I can't seem to replicate your issue, sorry.

**Comment by rfgamaral** [comment]
I just do something like this:

```
docker run -d \
    --name=gphotos-uploader \
    -e GPU_SCHEDULE="0 */8 * * *" \
    -v /absolute/path/to/config:/config \
    -v /absolute/path/to/photos:/photos \
    --restart unless-stopped \
    rfgamaral/gphotos-uploader
```

**Comment by rfgamaral** [comment]
Have you tried the command above @cirrusflyer ? Still not working for you?

**Comment by rfgamaral** [comment]
This issue is a bit stale and the OP doesn't reply back so I'm closing it for the moment. If @cirrusflyer comes back and/or someone else reports the same problem, I'll reopen it.
