### ISSUE TITLE
Unable to read configuration file (config.hjson)

### ISSUE THREAD

**Issue by Junyih** [rfgamaral/docker-gphotos-uploader#5]
I am running this on raspberry pi, In the step to run oauth.sh start, i got the following error:

```
docker exec -it gphotos-uploader oauth.sh start
Unable to read configuration file (~/.config/gphotos-uploader-cli/config.hjson).
Please review your configuration or execute 'gphotos-uploader-cli init' to create a new one.
```
then i changed volume '/config' to '/root/.config/gphotos-uploader-cli/' in container to put in my config file, i still get the same error..

when i use 'docker exec -it gphotos-uploader /bin/sh' to get in, i can 'cat ~/.config/gphotos-uploader-cli/config.hjson' and get correct content, but if i run 'gphotos-uploader-cli' i got this error. 

gphotos-uploader-cli seems got stuck finding the absolute path of '~/.config/gphotos-uploader-cli/config.hjson'?

'gphotos-uploader-cli init' couldn't create default config file either

```
gphotos-uploader-cli init
Failed to create the init config file: failed to get absolute path: ~/.config/gphotos-uploader-cli/config.hjson
```

**Comment by rfgamaral** [comment]
Please post you `docker run` command you initially used to create the container.

**Comment by Junyih** [comment]
*pi@veh16*:*~/docker/gphotos/conf $* docker run -d \

>     --name=gphotos-uploader \

>     -e GPU_SCHEDULE="0 */8 * * *" \

>     -v /home/pi/docker/gphotos/conf:/config \

>     -v /home/pi/photos:/photos \

>     --restart unless-stopped \

>     rfgamaral/gphotos-uploader

Unable to find image 'rfgamaral/gphotos-uploader:latest' locally

latest: Pulling from rfgamaral/gphotos-uploader

5b678b67777f: Pull complete

d9f0b2b885d9: Pull complete

a13912092536: Pull complete

3cf73ff34348: Pull complete

4ad9aba7b8e2: Pull complete

0a8d980bbadf: Pull complete

acef36171d5e: Pull complete

Digest:
sha256:ef34c7aded054a21356b831bc186383122e1b5ec63a3444d69c13ab343a6a54b

Status: Downloaded newer image for rfgamaral/gphotos-uploader:latest

8338c42fa15dbdc4858c132ccaec0b2aca81e47fe4d4dc8bfc9a0dd2cadc2de7

*pi@veh16*:*~/docker/gphotos/conf $* docker ps

CONTAINER ID        IMAGE                                      COMMAND
            CREATED             STATUS              PORTS
                                                NAMES

8338c42fa15d        rfgamaral/gphotos-uploader                 "/init"
            9 minutes ago       Up 9 minutes
                                                gphotos-uploader


*pi@veh16*:*~/docker/gphotos/conf $* pwd

/home/pi/docker/gphotos/conf

*pi@veh16*:*~/docker/gphotos/conf $* ls

config.hjson

*pi@veh16*:*~/docker/gphotos/conf $* docker exec -it gphotos-uploader
oauth.sh start

Unable to read configuration file
(~/.config/gphotos-uploader-cli/config.hjson).

Please review your configuration or execute 'gphotos-uploader-cli init' to
create a new one.

*pi@veh16*:*~/docker/gphotos/conf $* docker exec -it gphotos-uploader
gphotos-uploader-cli

Unable to read configuration file
(~/.config/gphotos-uploader-cli/config.hjson).

Please review your configuration or execute 'gphotos-uploader-cli init' to
create a new one.

*pi@veh16*:*~/docker/gphotos/conf $* docker exec -it gphotos-uploader sh

/ # cd /config

/config # ls

config.hjson

/ # cd /root/.config/gphotos-uploader-cli/

/config # ls

config.hjson

/config # gphotos-uploader-cli

Unable to read configuration file
(~/.config/gphotos-uploader-cli/config.hjson).

Please review your configuration or execute 'gphotos-uploader-cli init' to
create a new one.

/config # gphotos-uploader-cli init

Failed to create the init config file: failed to get absolute path:
~/.config/gphotos-uploader-cli/config.hjson

**Comment by rfgamaral** [comment]
Please login into the container with `docker exec -it gphotos-uploader sh` and post the output from the following commands:

- `whoami`
- `ls -l /`
- `ls -l /config`
- `cat /config/config.hjson`

**Comment by Junyih** [comment]
Hi,
Thank you for the reply, here it is, I masked my ID, secret and my email
from the config.


pi@veh16:~ $ docker exec -it gphotos-uploader sh
/ # whoami
root
/ # ls
bin      etc      lib      mnt      root     srv      usr
config   home     libexec  photos   run      sys      var
dev      init     media    proc     sbin     tmp
/ # ls -l
total 76
drwxr-xr-x    1 root     root          4096 Feb  8 16:04 bin
drwxr-xr-x    2 1000     1000          4096 May 26 11:25 config
drwxr-xr-x    5 root     root           320 May 26 21:43 dev
drwxr-xr-x    1 root     root          4096 May 26 21:43 etc
drwxr-xr-x    2 root     root          4096 Dec 20 21:34 home
-rwxr-xr-x    1 root     root           389 Sep  9  2018 init
drwxr-xr-x    1 root     root          4096 Dec 20 21:34 lib
drwxr-xr-x    2 root     root          4096 Feb  8 16:04 libexec
drwxr-xr-x    5 root     root          4096 Dec 20 21:34 media
drwxr-xr-x    2 root     root          4096 Dec 20 21:34 mnt
drwxr-xr-x    2 root     root          4096 May 26 11:26 photos
dr-xr-xr-x  158 root     root             0 May 26 21:43 proc
drwx------    1 root     root          4096 May 26 21:43 root
drwxr-xr-x    1 root     root          4096 May 26 21:43 run
drwxr-xr-x    2 root     root          4096 Dec 20 21:34 sbin
drwxr-xr-x    2 root     root          4096 Dec 20 21:34 srv
dr-xr-xr-x   12 root     root             0 May 26 21:43 sys
drwxrwxrwt    1 root     root          4096 Feb  8 16:04 tmp
drwxr-xr-x    1 root     root          4096 Feb  8 15:57 usr
drwxr-xr-x    1 root     root          4096 Dec 20 21:34 var
/ # ls -l /config
total 4
-rw-r--r--    1 root     1000           400 May 25 18:43 config.hjson
/ # cat /config/config.hjson
{
  APIAppCredentials: {
    ClientID:     "My ID.apps.googleusercontent.com",
    ClientSecret: "My secret",
  }
  jobs: [
    {
      account: my email @gmail.com
      sourceFolder: /photos
      makeAlbums: {
        enabled: false
        use: folderNames
      }
      deleteAfterUpload: true
      uploadVideos: true
    }
  ]
}
/ #

**Comment by rfgamaral** [comment]
Thank you!

For starters, there's something wrong here:

```
drwxr-xr-x    2 1000     1000          4096 May 26 11:25 config
```

It should be `root root` instead of `1000 1000`. Not sure why this is happening though...

One last output that I forgot in the previous post: `ls -l /root/.config`

**Comment by Junyih** [comment]
After i change the config file ownership from pi to root outside of docker, i see the file ownership inside docker is root root, but problem remains.

'''
/ # ls -l /config
total 8
-rw-r--r--    1 root     root           400 May 25 18:43 config.hjson
drwxr-xr-x    2 root     root          4096 May 27 17:00 uploads.db
/ # ls -l /root/.config/
total 0
lrwxrwxrwx    1 root     root             8 May 27 17:50 gphotos-uploader-cli -> /config/
/ # gphotos-uploader-cli 
Unable to read configuration file (~/.config/gphotos-uploader-cli/config.hjson).
Please review your configuration or execute 'gphotos-uploader-cli init' to create a new one.
'''

And, when i tried not to attach config folder to /config, stll the same problem

'''
pi@veh16:~/docker/gphotos/conf $ docker run -d --name=gphotos-uploader -e GPU_SCHEDULE="0 */1 * * *" -v /home/pi/photos:/photos  --restart unless-stopped rfgamaral/gphotos-uploader
pi@veh16:~/docker/gphotos/conf $ docker exec -it gphotos-uploader /bin/sh
/ # cd /config
/config # ls
/config # gphotos-uploader-cli init
Failed to create the init config file: failed to get absolute path: ~/.config/gphotos-uploader-cli/config.hjson
'''

**Comment by rfgamaral** [comment]
I can't replicate this issue and I really can't think of a reason why this is happening...

Do you have the latest Docker version installed? If not, could you try updating it, please?

**Comment by Junyih** [comment]
```
Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:17:57 2018
  OS/Arch:          linux/arm
  Experimental:     false
```

Thank you rfgamaral anway.

**Comment by Junyih** [comment]
i burned latest image 2019-04-08-raspbian-stretch-lite.zip, and installed docker by 
`curl -sSL https://get.docker.com | sh`, nothing else was done.

Still i got the error... :(

**Comment by rfgamaral** [comment]
@Junyih Updated the Docker image today, it includes many changes from the upstream project. Can you please try pulling the latest update, clean your workspace and try again to see if your problem is fixed?

**Comment by Junyih** [comment]
> @Junyih Updated the Docker image today, it includes many changes from the upstream project. Can you please try pulling the latest update, clean your workspace and try again to see if your problem is fixed?

Hi, Thank you for the update. I was on vocation so the response came late.

I got some new error this time...

`docker logs gphotos
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-oauth.sh-file: applying... 
execlineb: warning: too few arguments: expecting at least 6 but got 5
[fix-attrs.d] 01-oauth.sh-file: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-initialize-config: executing... 
/usr/local/bin/gphotos-uploader-cli: line 1: ELF: not found
/usr/local/bin/gphotos-uploader-cli: line 2: �H: not found
/usr/local/bin/gphotos-uploader-cli: line 2: �: not found
/usr/local/bin/gphotos-uploader-cli: line 2: ؠ�X�: not found
/usr/local/bin/gphotos-uploader-cli: line 2: �: not found
/usr/local/bin/gphotos-uploader-cli: line 2: @: not found
/usr/local/bin/gphotos-uploader-cli: line 3:O�����dtE: not found
/usr/local/bin/gphotos-uploader-cli: line 3: �: not found
/usr/local/bin/gphotos-uploader-cli: line 3: N�: not found
/usr/local/bin/gphotos-uploader-cli: line 3: �: not found
/usr/local/bin/gphotos-uploader-cli: line 3: ecHN�HNemNeg: not found
/usr/local/bin/gphotos-uploader-cli: line 1: syntax error: unterminated quoted string
sed: /config/config.hjson: No such file or directory
[cont-init.d] 10-initialize-config: exited 1.
[cont-init.d] 20-setup-crontab: executing... 
[cont-init.d] 20-setup-crontab: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
`

**Comment by rfgamaral** [comment]
This is really weird and I can't seem to reproduce any of this. Which Raspberry Pi are you running this on? The exact model please.

**Comment by Junyih** [comment]
> This is really weird and I can't seem to reproduce any of this. Which Raspberry Pi are you running this on? The exact model please.

Pi 3B with Raspbian Lite...

```
cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

```

**Comment by rfgamaral** [comment]
@Junyih Thank you!

I'm actually reviewing my images and I've done some stupid mistakes on the latest version and I'm working on fixing them. I'm also upgrading dependencies to latest version and a better architecture for the Raspberry Pi.

I'm hopeful these changes will fix your issue, please bear with me until I get this fixed and deployed :)

**Comment by Junyih** [comment]
Thank you rfgamaral, appreciate you are following this issue very much :)

**Comment by rfgamaral** [comment]
@Junyih Please try again and since I did some core architecture changes, please clean up your workspace and start fresh like you never tried to install this in the first place. Let me know how it goes :)

**Comment by Junyih** [comment]
Now the problem is like before :P 

```
~/docker/gphotos $ docker logs 09945ad1f53c
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-oauth.sh-file: applying... 
execlineb: warning: too few arguments: expecting at least 6 but got 5
[fix-attrs.d] 01-oauth.sh-file: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-initialize-config: executing... 
2019/07/23 17:09:57 Failed to create the init config file: failed to get absolute path: ~/.config/gphotos-uploader-cli/config.hjson
sed: /config/config.hjson: No such file or directory
[cont-init.d] 10-initialize-config: exited 1.
[cont-init.d] 20-setup-crontab: executing... 
[cont-init.d] 20-setup-crontab: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
pi@veh16:~/docker/gphotos $ 
```

**Comment by rfgamaral** [comment]
@Junyih Ok, let's do this one more time? 💪 

I've tweaked a few things related to the `config.hjson` file, not sure if they will fix your problem but they might 🤞 

Could you please try again?

**Comment by Junyih** [comment]
Hi! It worked this time!
And from the logs i saw it is uploading my photos now! 
Thank you rfgamaral, you are awesome!

**Comment by rfgamaral** [comment]
Finally ☺😊

**Comment by rfgamaral** [comment]
You might encounter issue #2 though and I have not yet found a fix for that one 😟
