### ISSUE TITLE
Update nmrshll/gphotos-uploader-cli

### ISSUE THREAD

**Issue by avidrissman** [rfgamaral/docker-gphotos-uploader#6]
As per https://github.com/nmrshll/gphotos-uploader-cli/issues/59, nmrshll/gphotos-uploader-cli upgraded some core libraries. Can you update the docker package?

**Comment by rfgamaral** [comment]
Will do as soon as I find some time available :)

**Comment by rfgamaral** [comment]
Waiting for https://github.com/nmrshll/gphotos-uploader-cli/issues/53 so I can properly update `gphotos-uploader-cli` and test it thoroughly...

**Comment by avidrissman** [comment]
You'll also need to wait for https://github.com/nmrshll/gphotos-uploader-cli/issues/64. `gphotos-uploader-cli` is rather broken at the moment :(

**Comment by beed2112** [comment]
@avidrissman  Are you running the version with your modifications?

**Comment by avidrissman** [comment]
@beed2112 You must have me mistaken for a different poster; I made no modifications.

**Comment by rfgamaral** [comment]
@avidrissman There's a new build in the oven (should be ready in 10mins or so) which includes a few workarounds for both issues described above. Please let me know how that works out for you :)

**Comment by avidrissman** [comment]
Comment when the new build is ready, and I'll give it a try. Thanks!

**Comment by rfgamaral** [comment]
> Comment when the new build is ready, and I'll give it a try. Thanks!

It's been ready for more than a day now 😄

**Comment by avidrissman** [comment]
I tried installing it earlier and fetched the “latest” tag. I just went to the [docker page](https://hub.docker.com/r/rfgamaral/gphotos-uploader/tags) and see that there are three new versions (“arm32v6-latest”, “arm64v8-latest”, and “amd64-latest”) from yesterday, and there is indeed a “latest” tag from 5 months ago!

If grabbing the “latest” tag is the wrong thing to do (as it seems to be), can you remove that tag so that people don’t accidentally use it? Have I been using a 5-months-old version all this time?

**Comment by rfgamaral** [comment]
> If grabbing the “latest” tag is the wrong thing to do (as it seems to be)

It's not, it's the correct one.

The `latest` tag is supposed to be a multi-architecture tag which will pick the correct architecture for your device (one of `arm32v6`, `arm64v8` or `amd64`). If you know the correct architecture for your device, you can pick that tag instead.

As for `latest`, I need to fix it, for some reason it wasn't updated automatically.

**Comment by rfgamaral** [comment]
The `latest` tag should now be fixed.

To be sure, pull `rfgamaral/gphotos-uploader:latest` and then do `docker inspect rfgamaral/gphotos-uploader:latest | grep 2019-06-28T11:20:49Z`. If you didn't get any output, it didn't work. Please let me know if that's the case.

**Comment by avidrissman** [comment]
I’m doing this on a Synology, and the UI collapsed the two rows of “latest” and “amd64-latest” into one. It’s also confirmed by the commandline.

**Comment by rfgamaral** [comment]
> and the UI collapsed the two rows of “latest” and “amd64-latest”

I also have a Synology and I have no idea what you meant with this 😞 

I'm also not sure if your problem is fixed or not, based on your response, can you please clarify?

**Comment by avidrissman** [comment]
There used to be two lines in the Synology UI, one with “latest” and one with “amd64-latest”. After the update of yours, now there’s one line with both tags, which indicates that they’re the same.

<img width="608" alt="Screen Shot 2019-07-02 at 11 36 33 AM" src="https://user-images.githubusercontent.com/3914435/60526178-cf2b8a80-9cbd-11e9-9b4d-1b401f7110eb.png">

I also ran the command you requested, for which you said:

> If you didn't get any output, it didn't work.

But I did get output, so I’m confirming it worked that way.

**Comment by rfgamaral** [comment]
Thank you for the clarification :)

**Comment by avidrissman** [comment]
FYI, every time it runs I see an error in the log about not having an auth token. I can authorize and authorize, and each time I auth it works once, and then continues to fail auth. The old version didn’t do that for me.

**Comment by rfgamaral** [comment]
> FYI, every time it runs I see an error in the log about not having an auth token. I can authorize and authorize, and each time I auth it works once, and then continues to fail auth. The old version didn’t do that for me.

Can you please open a new issue for that and describe it the best you can, please?

**Comment by rfgamaral** [comment]
@avidrissman Please follow #8 for the issue above :)

**Comment by avidrissman** [comment]
I will comment on that issue.

To be clear, the old version stayed authenticated for me. The new version does not.
