### ISSUE TITLE
Uploading suddenly failing with wrong status message found

### ISSUE THREAD

**Issue by gregbert42** [rfgamaral/docker-gphotos-uploader#7]
Everything has been working fine for a month or two.. suddenly this...

```
2019/06/28 19:21:32 Uploading IMG_0536.JPG
2019/06/28 19:21:36 failed uploading image
 --- at /go/src/github.com/nmrshll/gphotos-uploader-cli/upload/fileUpload.go:33 (StartFileUploadWorker.func1) ---
Caused by: failed uploading image
 --- at /go/src/github.com/nmrshll/gphotos-uploader-cli/upload/fileUpload.go:53 (FileUpload.upload) ---
Caused by: status message should be OK, found: Success
 --- at /go/src/github.com/nmrshll/google-photos-api-client-go/lib-gphotos/client.go:147 (Client.UploadFile)
```

created by

```bash
sudo docker create \
    --name=gphotos-uploader \
    -e GPU_SCHEDULE="0 */8 * * *" \
    -v /home/redacted/conf/gphotos:/config \
    -v /mnt/redacted/iCloud_Sync/:/photos:ro \
    --restart unless-stopped \
    rfgamaral/gphotos-uploader
```
with config.hjson

```hjson
{
  APIAppCredentials: {
    ClientID:     "redacted",
    ClientSecret: "redacted",
  }
  jobs: [
    {
      account: redacted
      sourceFolder: /photos
      makeAlbums: {
        enabled: true
        use: folderNames
      }
      deleteAfterUpload: false
      uploadVideos: true
    }
  ]
}
```

**Comment by rfgamaral** [comment]
Hi @gregbert42. This is an upstream issue (https://github.com/nmrshll/gphotos-uploader-cli/issues/64) and needs to be properly fixed there. However, I've worked around that issue in this container in the build I just deployed yesterday. Please make sure your container is using the latest version.

**Comment by gregbert42** [comment]
I deleted the image, and reformed the container. still same error

tried this too: gphotos-uploader-cli version, to try to get version. but only got:
gphotos-uploader-cli v0.0.0 (build: 0)

**Comment by gregbert42** [comment]
Ok - i see i needed to grab a specific tag, and not just default to 'latest' for the image. latest is 5 months old for some reason. but now its making me re-authenticate...

**Comment by rfgamaral** [comment]
> Ok - i see i needed to grab a specific tag, and not just default to 'latest' for the image. latest is 5 months old for some reason. but now its making me re-authenticate...

I screwed up somewhere and need to fix the latest tag, haven't had the time yet...

**Comment by rfgamaral** [comment]
The `latest` tag should now be fixed.

To be sure, pull `rfgamaral/gphotos-uploader:latest` and then do `docker inspect rfgamaral/gphotos-uploader:latest | grep 2019-06-28T11:20:49Z`. If you didn't get any output, it didn't work. Please let me know if that's the case.

**Comment by beed2112** [comment]
@rfgamaral     thaks for the updates.   i have been running rfgamaral/gphotos-uploader:amd64-latest for a few days now.  

I have started experiencing what seems like and auth time out  60 minutes after doing the auth process.



`2019/07/02 16:13:08 Need to log login into account myaccount@gmail.com
2019/07/02 16:13:10 You will now be taken to your browser for authentication or open the url below in a browser.
2019/07/02 16:13:10 https://accounts.google.com/o/oauth2<REDACTED>
2019/07/02 16:13:10 If you are opening the url manually on a different machine you will need to curl the result url on this machine manually.
2019/07/02 16:13:11 Failed to open browser, you MUST do the manual process.
2019/07/02 16:13:11 Authentication will be cancelled in 120 seconds
2019/07/02 16:14:00 Shutting down server...
2019/07/02 16:14:00 stored token for user: myaccount@gmail.com
Server gracefully stopped
2019/07/02 16:14:00 Entering Directory: /photos
2019/07/02 16:14:02 using album: photos / Id


<Upload activity initiated from command line>



[myid@myserver]# docker exec -it gphotos-uploader oauth.sh start
2019/07/02 17:13:59 No Dbus support
2019/07/02 17:13:59 Saving credentials in Leveldb
2019/07/02 17:13:59 Need to log login into account myaccount@gmail.com
2019/07/02 17:14:01 You will now be taken to your browser for authentication or open the url below in a browser.
2019/07/02 17:14:01 https://accounts.google.com/o/oauth2<REDACTED>
2019/07/02 17:14:01 If you are opening the url manually on a different machine you will need to curl the result url on this machine manually.
2019/07/02 17:14:02 Failed to open browser, you MUST do the manual process.
2019/07/02 17:14:02 Authentication will be cancelled in 120 seconds`

**Comment by rfgamaral** [comment]
@beed2112 Please open a new issue for that and try to detail the problem as good as possible. For instance, how are you sure that the authorization has timed out? Did the upload process stopped working? Anyway, we can discuss more if you post a new issue :)
