### ISSUE TITLE
Use offline access type

### ISSUE THREAD

**Issue by avidrissman** [rfgamaral/docker-gphotos-uploader#9]
Rather than having the URL redirect to a failed localhost page and having to paste in the entire broken URL to `/oauth.sh`, you should use `access_type=offline` to get a fancy result page that gives the token to copy/paste into the offline app.

**Comment by rfgamaral** [comment]
Interesting, will take a look at that as soon as I get the chance. Feel free to open a PR but make sure you test that it works 😄

**Comment by rfgamaral** [comment]
I didn't think much about it when you first posted this but this is an upstream issue. It needs to be implemented in `gphotos-uploader-cli` or one of its dependencies (probably `oauth2-noserver`).

**Comment by avidrissman** [comment]
Refiled.
